import type { Product } from '@/types';

export const products: Product[] = [
  // ===== Ciclo Escolar (Grados 1-3) =====
  { id: 1, cat: 'school', title: { es: 'Ajedrez 1er Grado', gl: 'Xadrez 1º Grao', en: 'Chess 1st Grade' }, desc: { es: '208 páginas A4 color. Reglas básicas y primeros conceptos para iniciarse en el ajedrez.', gl: '208 páxinas A4 cor. Regras básicas e primeiros conceptos.', en: '208 full-color A4 pages. Basic rules and first chess concepts.' }, price: '25,00 €', level: { es: 'Principiante', gl: 'Principiante', en: 'Beginner' }, levelClass: 'beginner', rating: '5.0', amazon: 'https://amzn.to/3u2HTvR', kindle: 'https://amzn.to/3rBLQ9d', emoji: '1️⃣' },
  { id: 2, cat: 'school', title: { es: 'Ajedrez 2º Grado', gl: 'Xadrez 2º Grao', en: 'Chess 2nd Grade' }, desc: { es: '180 páginas A4 color. Primeros maestros, táctica básica, anotación y competiciones.', gl: '180 páxinas A4 cor. Primeiros mestres, táctica básica, anotación e competicións.', en: '180 full-color A4 pages. Early masters, basic tactics, notation, competitions.' }, price: '25,00 €', level: { es: 'Principiante', gl: 'Principiante', en: 'Beginner' }, levelClass: 'beginner', rating: '5.0', amazon: 'https://amzn.to/3cBY6Cq', kindle: 'https://amzn.to/3m53yk9', emoji: '2️⃣' },
  { id: 3, cat: 'school', title: { es: 'Ajedrez 3er Grado', gl: 'Xadrez 3º Grao', en: 'Chess 3rd Grade' }, desc: { es: '184 páginas A4 color. Nivel ~1800 Elo. Complejidad del juego-ciencia y bagaje cultural.', gl: '184 páxinas A4 cor. Nivel ~1800 Elo. Complexidade do xogo-ciencia.', en: '184 full-color A4 pages. ~1800 Elo level. Depth of the game-science.' }, price: '25,00 €', level: { es: 'Intermedio', gl: 'Intermedio', en: 'Intermediate' }, levelClass: 'intermediate', rating: '5.0', amazon: 'https://amzn.to/3u7mDoy', kindle: 'https://amzn.to/3djfVoP', emoji: '3️⃣' },
  // ===== Maestría (Grados 4-7) =====
  { id: 4, cat: 'mastery', title: { es: 'Ajedrez 4º Grado', gl: 'Xadrez 4º Grao', en: 'Chess 4th Grade' }, desc: { es: 'Segundo ciclo. Análisis profundo, exigencia competitiva y visión estratégica.', gl: 'Segundo ciclo. Análise profunda, esixencia competitiva.', en: 'Second cycle. Deep analysis, competitive demands, strategic vision.' }, price: '27,00 €', level: { es: 'Intermedio', gl: 'Intermedio', en: 'Intermediate' }, levelClass: 'intermediate', rating: '5.0', amazon: 'https://amzn.to/3cyaqmY', kindle: 'https://amzn.to/3w5OUhj', emoji: '4️⃣' },
  { id: 5, cat: 'mastery', title: { es: 'Ajedrez 5º Grado', gl: 'Xadrez 5º Grao', en: 'Chess 5th Grade' }, desc: { es: '221 páginas. Aperturas, informática, idiomas y análisis de partidas.', gl: '221 páxinas. Aperturas, informática, idiomas.', en: '221 pages. Openings, computers, languages, game analysis.' }, price: '27,00 €', level: { es: 'Intermedio', gl: 'Intermedio', en: 'Intermediate' }, levelClass: 'intermediate', rating: '5.0', amazon: 'https://amzn.to/3cAbYgs', kindle: 'https://amzn.to/3rvzfV3', emoji: '5️⃣' },
  { id: 6, cat: 'mastery', title: { es: 'Ajedrez 6º Grado', gl: 'Xadrez 6º Grao', en: 'Chess 6th Grade' }, desc: { es: '250 páginas. Camino hacia los 2200 FIDE. 180 partidas analizadas.', gl: '250 páxinas. Camiño cara os 2200 FIDE. 180 partidas analizadas.', en: '250 pages. Path to 2200 FIDE. 180 analyzed games.' }, price: '30,00 €', level: { es: 'Avanzado', gl: 'Avanzado', en: 'Advanced' }, levelClass: 'advanced', rating: '5.0', amazon: 'https://amzn.to/3wehTPO', kindle: 'https://amzn.to/2PDMC8g', emoji: '6️⃣' },
  { id: 7, cat: 'mastery', title: { es: 'Ajedrez 7º Grado', gl: 'Xadrez 7º Grao', en: 'Chess 7th Grade' }, desc: { es: 'Introducción al semi-profesionalismo. Voz autorizada a nivel técnico internacional.', gl: 'Introdución ao semi-profesionalismo.', en: 'Introduction to semi-professionalism.' }, price: '30,00 €', level: { es: 'Avanzado', gl: 'Avanzado', en: 'Advanced' }, levelClass: 'advanced', rating: '5.0', amazon: 'https://amzn.to/39rVJzY', kindle: 'https://amzn.to/3dfwT7G', emoji: '7️⃣' },
  // ===== Gran Maestría (Grados 8-10) =====
  { id: 8, cat: 'grandmaster', title: { es: 'Ajedrez 8º Grado', gl: 'Xadrez 8º Grao', en: 'Chess 8th Grade' }, desc: { es: 'Era de Tal, Petrosian, Spassky. Más de 200 páginas de análisis.', gl: 'Era de Tal, Petrosian, Spassky.', en: 'Tal, Petrosian, Spassky era. 200+ pages.' }, price: '30,00 €', level: { es: 'Avanzado', gl: 'Avanzado', en: 'Advanced' }, levelClass: 'advanced', rating: '5.0', amazon: 'https://amzn.to/2O6OLcj', kindle: 'https://amzn.to/3u7faWF', emoji: '8️⃣' },
  { id: 9, cat: 'grandmaster', title: { es: 'Ajedrez 9º Grado', gl: 'Xadrez 9º Grao', en: 'Chess 9th Grade' }, desc: { es: 'Karpov vs Korchnoi, geopolítica del ajedrez, la Guerra Fría en el tablero.', gl: 'Karpov vs Korchnoi, xeopolítica do xadrez.', en: 'Karpov vs Korchnoi, chess geopolitics, Cold War.' }, price: '30,00 €', level: { es: 'Profesional', gl: 'Profesional', en: 'Professional' }, levelClass: 'professional', rating: '5.0', amazon: 'https://amzn.to/2O5Po5L', kindle: 'https://amzn.to/39rduzu', emoji: '9️⃣' },
  { id: 10, cat: 'grandmaster', title: { es: 'Ajedrez 10º Grado', gl: 'Xadrez 10º Grao', en: 'Chess 10th Grade' }, desc: { es: 'Años 80, las "2Ks", tesis sobre talento vs método. Cierra el círculo.', gl: 'Anos 80, as "2Ks", tese talento vs método.', en: 'The 80s, the "2Ks", talent vs method thesis.' }, price: '30,00 €', level: { es: 'Profesional', gl: 'Profesional', en: 'Professional' }, levelClass: 'professional', rating: '5.0', amazon: 'https://amzn.to/3wemqBM', kindle: 'https://amzn.to/3fv94eD', emoji: '🔟' },
  // ===== Libros Avanzados =====
  { id: 11, cat: 'projects', title: { es: 'Ajedrez Educativo', gl: 'Xadrez Educativo', en: 'Educational Chess' }, desc: { es: 'Pedagogía digital y sinergias educativas. Inmersión en la enseñanza del ajedrez.', gl: 'Pedagoxía dixital e sinerxías educativas.', en: 'Digital pedagogy and educational synergies.' }, price: '40,00 €', level: { es: 'Avanzado', gl: 'Avanzado', en: 'Advanced' }, levelClass: 'advanced', rating: '5.0', amazon: 'https://amzn.to/44jM6Ns', kindle: 'https://amzn.to/3ss4Vk0', emoji: '📚' },
  { id: 12, cat: 'projects', title: { es: 'CiberAjedrez', gl: 'CiberXadrez', en: 'CyberChess' }, desc: { es: 'IA + Ajedrez. Motores +3600 Elo. Análisis técnico avanzado del nuevo ciberajedrez.', gl: 'IA + Xadrez. Motores +3600 Elo.', en: 'AI + Chess. +3600 Elo engines. Advanced technical analysis.' }, price: '40,00 €', level: { es: 'Profesional', gl: 'Profesional', en: 'Professional' }, levelClass: 'professional', rating: '5.0', amazon: 'https://amzn.to/45ihsp1', kindle: 'https://amzn.to/3E4VoC8', emoji: '🤖' },
  { id: 13, cat: 'projects', title: { es: 'Ajedrez Salvaje', gl: 'Xadrez Salvaxe', en: 'Wild Chess' }, desc: { es: 'Ataque y creatividad. Las partidas más salvajes del ajedrez mundial analizadas con IA.', gl: 'Ataque e creatividade. As partidas máis salvaxes do xadrez.', en: 'Attack and creativity. The wildest chess games analyzed with AI.' }, price: '32,17 €', level: { es: 'Profesional', gl: 'Profesional', en: 'Professional' }, levelClass: 'professional', rating: '5.0', amazon: 'https://www.amazon.com/AJEDREZ-SALVAJE-Proyecto-Educativo-Ajedrez/dp/B0D7CTTR2D', kindle: '', emoji: '⚔️' },
  { id: 14, cat: 'projects', title: { es: 'Tablas Inmortales', gl: 'Táboas Inmortais', en: 'Immortal Draws' }, desc: { es: 'Las tablas más brillantes de la historia. Sacrificios y precisión en el límite del empate.', gl: 'As táboas máis brillantes da historia.', en: 'The most brilliant draws in history. Sacrifices and precision at the draw limit.' }, price: '32,17 €', level: { es: 'Profesional', gl: 'Profesional', en: 'Professional' }, levelClass: 'professional', rating: '5.0', amazon: 'https://www.amazon.com/TABLAS-INMORTALES-Proyecto-Educativo-Ajedrez-ebook/dp/B0F941VF5Q', kindle: '', emoji: '🤝' },
  { id: 15, cat: 'projects', title: { es: 'Ajedrez y Política', gl: 'Xadrez e Política', en: 'Chess and Politics' }, desc: { es: 'Geopolítica del ajedrez. Cómo los regímenes y las ideologías influyeron en el juego.', gl: 'Xeopolítica do xadrez. Como os réximes influíron no xogo.', en: 'Chess geopolitics. How regimes and ideologies shaped the game.' }, price: '32,17 €', level: { es: 'Profesional', gl: 'Profesional', en: 'Professional' }, levelClass: 'professional', rating: '5.0', amazon: 'https://www.amazon.com/AJEDREZ-POL%C3%8DTICA-Proyecto-Educativo-Ajedrez/dp/B0F9DNW6F3', kindle: '', emoji: '🏛️' },
  // ===== Chess Organizers =====
  { id: 16, cat: 'projects', title: { es: 'Chess Organizers 1.0', gl: 'Chess Organizers 1.0', en: 'Chess Organizers 1.0' }, desc: { es: 'Manual de excelencia para organizadores de torneos. 675 páginas de gestión profesional.', gl: 'Manual de excelencia para organizadores de torneos.', en: 'Excellence manual for tournament organizers. 675 pages.' }, price: '56,34 €', level: { es: 'Profesional', gl: 'Profesional', en: 'Professional' }, levelClass: 'professional', rating: '5.0', amazon: 'https://www.amazon.com/MANUAL-EXCELENCIA-CHESS-ORGANIZERS-Spanish/dp/B0GTD3XPFY', kindle: '', emoji: '🏆', image: '/chess-organizers.jpg' },
  // ===== Ajedrez y Matemáticas (Isabel López Martínez) =====
  { id: 17, cat: 'math', title: { es: 'Ajedrez y Matemáticas 1', gl: 'Xadrez e Matemáticas 1', en: 'Chess and Math 1' }, desc: { es: 'Primer volumen de la serie. Patrones numéricos en el tablero, geometría de las piezas y lógica matemática aplicada al ajedrez.', gl: 'Primeiro volume da serie. Patróns numéricos no taboleiro, xeometría das pezas e lóxica matemática.', en: 'First volume of the series. Number patterns on the board, piece geometry, and mathematical logic applied to chess.' }, price: '14,90 €', level: { es: 'Principiante', gl: 'Principiante', en: 'Beginner' }, levelClass: 'beginner', rating: '5.0', amazon: 'https://amzn.to/4v09DQY', kindle: '', emoji: '➕' },
  { id: 18, cat: 'math', title: { es: 'Ajedrez y Matemáticas 2', gl: 'Xadrez e Matemáticas 2', en: 'Chess and Math 2' }, desc: { es: 'Segundo volumen. Probabilidad, combinatoria y estrategia algorítmica a través del ajedrez.', gl: 'Segundo volume. Probabilidade, combinatoria e estratexia algorítmica.', en: 'Second volume. Probability, combinatorics, and algorithmic strategy through chess.' }, price: '14,90 €', level: { es: 'Intermedio', gl: 'Intermedio', en: 'Intermediate' }, levelClass: 'intermediate', rating: '5.0', amazon: 'https://amzn.to/4uNpOAE', kindle: '', emoji: '✖️' },
  { id: 19, cat: 'math', title: { es: 'Ajedrez y Matemáticas 3', gl: 'Xadrez e Matemáticas 3', en: 'Chess and Math 3' }, desc: { es: 'Tercer volumen. Teoría de juegos, inteligencia artificial y resolución de problemas complejos.', gl: 'Terceiro volume. Teoría de xogos, intelixencia artificial e resolución de problemas.', en: 'Third volume. Game theory, artificial intelligence, and complex problem solving.' }, price: '14,90 €', level: { es: 'Avanzado', gl: 'Avanzado', en: 'Advanced' }, levelClass: 'advanced', rating: '5.0', amazon: 'https://amzn.to/4vnXTIG', kindle: '', emoji: '🔢' },
  // ===== Cuento Infantil (Isabel López Martínez) =====
  { id: 20, cat: 'projects', title: { es: 'Salvemos al Rey Blanco', gl: 'Salvemos ao Rei Branco', en: 'Save the White King' }, desc: { es: 'Cuento infantil. Una emocionante aventura de ajedrez para los más pequeños. Ideal para iniciarse en el mundo del ajedrez de forma divertida.', gl: 'Conto infantil. Unha emocionante aventura de xadrez para os máis pequenos.', en: "Children's story. An exciting chess adventure for young kids. Perfect for starting chess in a fun way." }, price: '10,99 €', level: { es: 'Infantil', gl: 'Infantil', en: 'Children' }, levelClass: 'beginner', rating: '5.0', amazon: 'https://amzn.to/4ewRqnG', kindle: '', emoji: '👑', image: '/cuento-ajedrez.jpg' },
];

export function getProductById(id: number): Product | undefined {
  return products.find(p => p.id === id);
}

export function getProductsByCategory(cat: string): Product[] {
  if (cat === 'all') return products;
  return products.filter(p => p.cat === cat);
}
