import type { Product } from '@/types';

export const products: Product[] = [
  { id: 1, cat: 'school', title: { es: 'Ajedrez 1er Grado', gl: 'Xadrez 1º Grao', en: 'Chess 1st Grade' }, desc: { es: 'Primer volumen · 208 páginas A4 color. Reglas básicas y primeros conceptos para iniciarse en el ajedrez.', gl: 'Primeiro volume · 208 páxinas A4 cor. Regras básicas e primeiros conceptos.', en: 'First volume · 208 full-color A4 pages. Basic rules and first concepts.' }, price: '25,00 €', level: { es: 'Principiante', gl: 'Principiante', en: 'Beginner' }, levelClass: 'beginner', rating: '5.0', amazon: 'https://amzn.to/3u2HTvR', kindle: 'https://amzn.to/3rBLQ9d', emoji: '📘' },
  { id: 2, cat: 'school', title: { es: 'Ajedrez 2º Grado', gl: 'Xadrez 2º Grao', en: 'Chess 2nd Grade' }, desc: { es: '180 páginas A4 color. Primeros maestros, táctica básica, anotación y competiciones.', gl: '180 páxinas A4 cor. Primeiros mestres, táctica básica, anotación e competicións.', en: '180 full-color A4 pages. Early masters, basic tactics, notation, competitions.' }, price: '25,00 €', level: { es: 'Principiante', gl: 'Principiante', en: 'Beginner' }, levelClass: 'beginner', rating: '5.0', amazon: 'https://amzn.to/3cBY6Cq', kindle: 'https://amzn.to/3m53yk9', emoji: '📘' },
  { id: 3, cat: 'school', title: { es: 'Ajedrez 3er Grado', gl: 'Xadrez 3º Grao', en: 'Chess 3rd Grade' }, desc: { es: '184 páginas A4 color. Nivel ~1800 Elo. Complejidad del juego-ciencia y bagaje cultural.', gl: '184 páxinas A4 cor. Nivel ~1800 Elo. Complexidade do xogo-ciencia.', en: '184 full-color A4 pages. ~1800 Elo level. Depth of the game-science.' }, price: '25,00 €', level: { es: 'Intermedio', gl: 'Intermedio', en: 'Intermediate' }, levelClass: 'intermediate', rating: '5.0', amazon: 'https://amzn.to/3u7mDoy', kindle: 'https://amzn.to/3djfVoP', emoji: '📘' },
  { id: 4, cat: 'mastery', title: { es: 'Ajedrez 4º Grado', gl: 'Xadrez 4º Grao', en: 'Chess 4th Grade' }, desc: { es: 'Segundo ciclo. Análisis profundo, exigencia competitiva y visión estratégica.', gl: 'Segundo ciclo. Análise profunda, esixencia competitiva.', en: 'Second cycle. Deep analysis, competitive demands.' }, price: '27,00 €', level: { es: 'Intermedio', gl: 'Intermedio', en: 'Intermediate' }, levelClass: 'intermediate', rating: '5.0', amazon: 'https://amzn.to/3cyaqmY', kindle: 'https://amzn.to/3w5OUhj', emoji: '📗' },
  { id: 5, cat: 'mastery', title: { es: 'Ajedrez 5º Grado', gl: 'Xadrez 5º Grao', en: 'Chess 5th Grade' }, desc: { es: '221 páginas. Aperturas, informática, idiomas y análisis de partidas.', gl: '221 páxinas. Aperturas, informática, idiomas.', en: '221 pages. Openings, computers, languages, game analysis.' }, price: '27,00 €', level: { es: 'Intermedio', gl: 'Intermedio', en: 'Intermediate' }, levelClass: 'intermediate', rating: '5.0', amazon: 'https://amzn.to/3cAbYgs', kindle: 'https://amzn.to/3rvzfV3', emoji: '📗' },
  { id: 6, cat: 'mastery', title: { es: 'Ajedrez 6º Grado', gl: 'Xadrez 6º Grao', en: 'Chess 6th Grade' }, desc: { es: '250 páginas. Camino hacia los 2200 FIDE. 180 partidas analizadas.', gl: '250 páxinas. Camiño cara os 2200 FIDE. 180 partidas analizadas.', en: '250 pages. Path to 2200 FIDE. 180 analyzed games.' }, price: '30,00 €', level: { es: 'Avanzado', gl: 'Avanzado', en: 'Advanced' }, levelClass: 'advanced', rating: '5.0', amazon: 'https://amzn.to/3wehTPO', kindle: 'https://amzn.to/2PDMC8g', emoji: '📗' },
  { id: 7, cat: 'mastery', title: { es: 'Ajedrez 7º Grado', gl: 'Xadrez 7º Grao', en: 'Chess 7th Grade' }, desc: { es: 'Introducción al semi-profesionalismo. Voz autorizada a nivel técnico internacional.', gl: 'Introdución ao semi-profesionalismo.', en: 'Introduction to semi-professionalism.' }, price: '30,00 €', level: { es: 'Avanzado', gl: 'Avanzado', en: 'Advanced' }, levelClass: 'advanced', rating: '5.0', amazon: 'https://amzn.to/39rVJzY', kindle: 'https://amzn.to/3dfwT7G', emoji: '📗' },
  { id: 8, cat: 'grandmaster', title: { es: 'Ajedrez 8º Grado', gl: 'Xadrez 8º Grao', en: 'Chess 8th Grade' }, desc: { es: 'Era de Tal, Petrosian, Spassky. Más de 200 páginas de análisis profundo.', gl: 'Era de Tal, Petrosian, Spassky.', en: 'Tal, Petrosian, Spassky era. 200+ pages.' }, price: '30,00 €', level: { es: 'Avanzado', gl: 'Avanzado', en: 'Advanced' }, levelClass: 'advanced', rating: '5.0', amazon: 'https://amzn.to/2O6OLcj', kindle: 'https://amzn.to/3u7faWF', emoji: '📕' },
  { id: 9, cat: 'grandmaster', title: { es: 'Ajedrez 9º Grado', gl: 'Xadrez 9º Grao', en: 'Chess 9th Grade' }, desc: { es: 'Karpov vs Korchnoi, geopolítica del ajedrez, la guerra fría en el tablero.', gl: 'Karpov vs Korchnoi, xeopolítica do xadrez.', en: 'Karpov vs Korchnoi, chess geopolitics, Cold War.' }, price: '30,00 €', level: { es: 'Profesional', gl: 'Profesional', en: 'Professional' }, levelClass: 'professional', rating: '5.0', amazon: 'https://amzn.to/2O5Po5L', kindle: 'https://amzn.to/39rduzu', emoji: '📕' },
  { id: 10, cat: 'grandmaster', title: { es: 'Ajedrez 10º Grado', gl: 'Xadrez 10º Grao', en: 'Chess 10th Grade' }, desc: { es: 'Años 80, las "2Ks", tesis sobre talento vs método. El libro que cierra el círculo.', gl: 'Anos 80, as "2Ks", tese talento vs método.', en: 'The 80s, the "2Ks", talent vs method thesis.' }, price: '30,00 €', level: { es: 'Profesional', gl: 'Profesional', en: 'Professional' }, levelClass: 'professional', rating: '5.0', amazon: 'https://amzn.to/3wemqBM', kindle: 'https://amzn.to/3fv94eD', emoji: '📕' },
  { id: 11, cat: 'projects', title: { es: 'Salvemos al Rey Blanco', gl: 'Salvemos ao Rei Branco', en: 'Save the White King' }, desc: { es: 'Aventura infantil para aprender ajedrez. Los niños ayudan a la Dama Blanca a rescatar al Rey.', gl: 'Aventura infantil para aprender xadrez.', en: "Children's adventure to learn chess." }, price: '10,99 €', level: { es: 'Principiante', gl: 'Principiante', en: 'Beginner' }, levelClass: 'beginner', rating: '5.0', amazon: 'https://amzn.to/2Q8CvJk', kindle: 'https://amzn.to/33vt9ua', emoji: '👑' },
  { id: 12, cat: 'projects', title: { es: 'Ajedrez Educativo', gl: 'Xadrez Educativo', en: 'Educational Chess' }, desc: { es: 'Pedagogía digital y sinergias educativas. Inmersión en el ajedrez en la educación.', gl: 'Pedagoxía dixital e sinerxías educativas.', en: 'Digital pedagogy and educational synergies.' }, price: '40,00 €', level: { es: 'Avanzado', gl: 'Avanzado', en: 'Advanced' }, levelClass: 'advanced', rating: '5.0', amazon: 'https://amzn.to/44jM6Ns', kindle: 'https://amzn.to/3ss4Vk0', emoji: '📚' },
  { id: 13, cat: 'projects', title: { es: 'CiberAjedrez', gl: 'CiberXadrez', en: 'CyberChess' }, desc: { es: 'IA + Ajedrez. Motores +3600 Elo. Análisis técnico avanzado del nuevo ciberajedrez.', gl: 'IA + Xadrez. Motores +3600 Elo.', en: 'AI + Chess. +3600 Elo engines. Advanced technical analysis.' }, price: '40,00 €', level: { es: 'Profesional', gl: 'Profesional', en: 'Professional' }, levelClass: 'professional', rating: '5.0', amazon: 'https://amzn.to/45ihsp1', kindle: 'https://amzn.to/3E4VoC8', emoji: '🤖' },
];

export function getProductById(id: number): Product | undefined {
  return products.find(p => p.id === id);
}

export function getProductsByCategory(cat: string): Product[] {
  if (cat === 'all') return products;
  return products.filter(p => p.cat === cat);
}
